[deploy]
releaseCommand = "php artisan storage:link --force && php artisan migrate --force"
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/admin/login"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
