[deploy]
releaseCommand = "php artisan storage:link --force && php artisan migrate --force"
startCommand = "php -d upload_max_filesize=100M -d post_max_size=100M -d memory_limit=512M -S 0.0.0.0:$PORT -t public server.php"
healthcheckPath = "/admin/login"
